# Generated by Django 3.0.3 on 2020-04-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200418_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='state_address',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
