# Generated by Django 3.0.3 on 2020-04-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200418_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip_address',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
