# Generated by Django 3.0.3 on 2020-04-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='duration',
            new_name='date',
        ),
    ]
